---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_core::default]
      - recipe[gusztavvargadr_workstations_git::default]
    attributes:
      gusztavvargadr_workstations_core:
        tools:
          chocolatey:
            git:
              version: 2.11.1
              install:
                params: "'/GitAndUnixToolsOnPath /NoShellIntegration'"
      gusztavvargadr_workstations_git:
        profiles:
          workspaces:
            github:
              address: https://github.com/github
              directory: /Users/vagrant/Repos/github
              repositories:
                gitignore:
