driver:
  name: vagrant
  vagrantfiles:
    - ../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_core::default]
      - recipe[gusztavvargadr_workstations_dockerc::default]
    attributes:
      gusztavvargadr_workstations_core:
        requirements:
          features:
            Microsoft-Hyper-V:
            Microsoft-Hyper-V-Management-Clients:
            Microsoft-Hyper-V-Management-PowerShell:
            RSAT-Hyper-V-Tools-Feature:
            Containers:
        tools:
          windows:
            Docker for Windows (Edge):
              source: https://download.docker.com/win/edge/Docker%20for%20Windows%20Installer.exe
              install:
                - install
                - --quiet
              directory: /Program Files/Docker
      gusztavvargadr_workstations_dockerc:
        profiles:
          images:
            hello-world:
