directory = File.dirname(__FILE__)
require "#{directory}/../../../../Berksfile.core"

source 'https://supermarket.chef.io'

workstations_cookbook 'components', 'core'
workstations_cookbook 'components', 'dockerc'

cookbook 'windows'
