---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_core::default]
      - recipe[gusztavvargadr_workstations_aws::default]
    attributes:
      gusztavvargadr_workstations_core:
        tools:
          chocolatey:
            awscli:
      gusztavvargadr_workstations_aws:
        profiles:
          workspaces:
            default:
              access_key_id: access_key_id
              secret_access_key: secret_access_key
              region: us-east-1
