---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_core::default]
    attributes:
      gusztavvargadr_workstations_core:
        requirements:
          features:
            TelnetClient:
        tools:
          chocolatey:
            nuget.commandline:
            terraform:
              version: 0.8.8
            git:
              install:
                ignorechecksum:
                params: "'/GitAndUnixToolsOnPath /NoShellIntegration'"
            powershell:
              elevated: true
          windows:
            .NET Core SDK:
              source: https://download.microsoft.com/download/B/9/F/B9F1AF57-C14A-4670-9973-CDF47209B5BF/dotnet-dev-win-x64.1.0.4.exe
              install:
                - /install
                - /quiet
                - /norestart
              directory: /Program Files/dotnet
            SQL Server Management Studio 16:
              source: https://download.microsoft.com/download/9/3/3/933EA6DD-58C5-4B78-8BEC-2DF389C72BE0/SSMS-Setup-ENU.exe
              install:
                - /install
                - /quiet
                - /norestart
              directory: /Program Files (x86)/Microsoft SQL Server/130/Tools/Binn/ManagementStudio
              elevated: true
          files:
            file:///Windows/System32/drivers/etc/hosts: /Users/vagrant/AppData/Local/Temp/hosts
