---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_core::default]
      - recipe[gusztavvargadr_workstations_svn::default]
    attributes:
      gusztavvargadr_workstations_core:
        tools:
          chocolatey:
            svn:
      gusztavvargadr_workstations_svn:
        profiles:
          workspaces:
            apache:
              address: http://svn.apache.org/repos
              directory: /Users/vagrant/Repos/apache
              repositories:
                asf/logging/log4net/trunk:
