directory = File.dirname(__FILE__)
require "#{directory}/../../Berksfile.core"

source 'https://supermarket.chef.io'

workstations_cookbook 'components', 'core'
workstations_cookbook 'components', 'os'
workstations_cookbook 'components', 'nuget'
workstations_cookbook 'components', 'vagrant'
workstations_cookbook 'components', 'dockere'
workstations_cookbook 'components', 'aws'
workstations_cookbook 'components', 'git'
workstations_cookbook 'components', 'svn'

cookbook 'windows'
