---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_core::default]
      - recipe[gusztavvargadr_workstations_nuget::default]
    attributes:
      gusztavvargadr_workstations_core:
        tools:
          chocolatey:
            nuget.commandline:
      gusztavvargadr_workstations_nuget:
        profiles:
          workspaces:
            dotnet:
              address: https://dotnet.myget.org/F
              sources:
                aspnetcore-dev:
                  address: aspnetcore-dev/api/v3/index.json
