core:
  includes:
    - components/vagrant/core
  chef:
    json:
      workstations_core:
        tools:
          chocolatey:
            chefdk:
            packer:
      workstations_vagrant:
        profiles:
          plugins:
            vagrant-reload:
            vagrant-berkshelf:

dockerc:
  includes:
    - stacks/infrastructure/core
    - components/dockerc/core

dockere:
  includes:
    - stacks/infrastructure/core
    - components/dockere/core

virtualbox:
  includes:
    - stacks/infrastructure/core
  chef:
    json:
      workstations_core:
        tools:
          chocolatey:
            virtualbox:

aws:
  includes:
    - stacks/infrastructure/core
    - components/aws/core
  chef:
    json:
      workstations_core:
        tools:
          chocolatey:
            terraform:
      workstations_vagrant:
        profiles:
          plugins:
            vagrant-aws:
          boxes:
            dummy:
              address: file:///vagrant-workstations/src/boxes/dummy.json
