driver:
  name: vagrant
  vagrantfiles:
    - ../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_core::default]
      - recipe[gusztavvargadr_workstations_dockere::default]
    attributes:
      gusztavvargadr_workstations_core:
        requirements:
          features:
            Containers:
      gusztavvargadr_workstations_dockere:
        profiles:
          images:
            hello-world:nanoserver:
