---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_workstations_core::default]
      - recipe[gusztavvargadr_workstations_vagrant::default]
    attributes:
      gusztavvargadr_workstations_core:
        tools:
          chocolatey:
            vagrant:
              install:
                ignorepackagecodes:
      gusztavvargadr_workstations_vagrant:
        profiles:
          plugins:
            vagrant-reload:
          boxes:
            ubuntu/trusty32:
